types:
    Book:
        parent: false
        properties:
            isbn: ~
            title: { nullable: false }
            description: { nullable: false }
            author: { range: Text, nullable: false }
            publicationDate: { nullable: false }
    Review:
        parent: false
        properties:
            reviewBody: ~
            rating: { range: Integer, nullable: false } # This is a custom field that doesn't exist in the vocab
            book: { range: Book, nullable: false, cardinality: '(*..1)' }
